<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No, thanks</name>
   <tag></tag>
   <elementGuidId>3ae052dc-3608-4cb9-a58d-11c4a9f88093</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userflowjs-bubble-content']/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.userflowjs-bubble-button.userflowjs-bubble-button--default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7442ef8-53f1-4739-9d38-556950518969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userflowjs-bubble-button userflowjs-bubble-button--default</value>
      <webElementGuid>265e9047-15fd-4b0c-821e-50f2f8a60e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No, thanks</value>
      <webElementGuid>34628665-0f03-4f34-af87-d517e5e30f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userflowjs-bubble-content&quot;)/div[@class=&quot;userflowjs-bubble-buttons&quot;]/button[@class=&quot;userflowjs-bubble-button userflowjs-bubble-button--default&quot;]</value>
      <webElementGuid>1eb6315b-d527-44d1-855b-5afd3da04192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboard - Katalon TestOps/iframe_View all_userflowjs-bubble__frame</value>
      <webElementGuid>9214d674-0629-4434-8e32-b140bb18688c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userflowjs-bubble-content']/div/button</value>
      <webElementGuid>ecece865-d656-441c-ad08-caf69258269c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resume'])[1]/preceding::button[1]</value>
      <webElementGuid>ff613f77-a148-41b9-80d2-a95341a125c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4a4444dd-a227-49bb-9df7-2bb16cac9c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'No, thanks' or . = 'No, thanks')]</value>
      <webElementGuid>5b83d117-2b3d-4937-a6c0-b1be6b01c801</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
