<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test ActivitiesFromTo</name>
   <tag></tag>
   <elementGuidId>79cccf64-f87b-4cc3-8d16-4f6a43d310f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.d-flex</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9e9138d-01c1-4c98-8362-e2939c2b775e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex</value>
      <webElementGuid>ab60d48b-1c78-409b-ba37-86d056afbb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>9967f9c7-1db6-4194-bd96-a727b8783038</value>
      <webElementGuid>a24efe56-7de6-49ab-a8bf-d942a0373117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test ActivitiesFrom​To​</value>
      <webElementGuid>f05794b9-20e5-4373-91c7-6c1eae19ed08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;no-card card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-flex&quot;]</value>
      <webElementGuid>49c14fb9-4af8-4ef4-805b-015e4b458d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div</value>
      <webElementGuid>226a4493-2653-4a24-8d71-7e53bbb77453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::div[5]</value>
      <webElementGuid>8a199072-b0ca-4635-a8a5-134064c80280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::div[7]</value>
      <webElementGuid>ed225cae-7251-4b89-8902-8e58eabd4cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>d59a27c7-b25f-44fd-af34-ed3d1dad7bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Test ActivitiesFrom​To​' or . = 'Test ActivitiesFrom​To​')]</value>
      <webElementGuid>4f3787ff-bb49-4d2f-9c8e-378e1afebe19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
