<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_View all_userflowjs-bubble__frame</name>
   <tag></tag>
   <elementGuidId>adba6faf-cbc8-4ae2-97c8-b8fc3c749846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userflow-ui']/div/div/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.userflowjs-bubble__frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e6e68c36-0c4d-4d5e-8532-031232007ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>0cb44d52-33e9-4779-a3df-5c9469e7c7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userflowjs-bubble__frame</value>
      <webElementGuid>7abe3f44-f524-497e-a8ad-300dd6f82548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4cbce821-3faf-4200-8f77-85c3da3a0d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_size</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>125d00be-1e36-404e-b2fc-3147a4f2f2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>3d88c4a4-5446-4f48-af20-6fdad4a88132</value>
      <webElementGuid>76315fc9-b6f1-424c-ad81-b3399cba85a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userflow-ui&quot;)/div[@class=&quot;userflowjs-flow-chrome userflowjs-theme-root userflowjs-flow-chrome--position-fixed userflowjs-flow-chrome--appearance-modal&quot;]/div[@class=&quot;userflowjs-bubble&quot;]/div[@class=&quot;userflowjs-bubble-outline userflowjs-bubble-outline--bubble-placement-bottom-right&quot;]/div[@class=&quot;userflowjs-bubble__frame-wrapper&quot;]/iframe[@class=&quot;userflowjs-bubble__frame&quot;]</value>
      <webElementGuid>276ee90c-d233-429e-bccc-32390271efdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userflow-ui']/div/div/div/div/iframe</value>
      <webElementGuid>1a1b7d54-b29d-4f56-b165-1ed8635c5ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>01067df7-e399-4e34-9260-31e1b7de151f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
