<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_View all_userflowjs-resource-center-_f0d70f</name>
   <tag></tag>
   <elementGuidId>a3e34137-75e3-4667-8262-a95721b8fc80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userflow-ui']/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.userflowjs-resource-center-frame.userflowjs-resource-center-frame--fixed.userflowjs-resource-center-frame--placement-bottom-right.userflowjs-resource-center-frame--animating.userflowjs-resource-center-frame--closed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2dc27c7c-93c7-4df2-8810-4cbb46088162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>3cd4b14c-4e6c-4c46-b4d3-fca40f412cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userflowjs-resource-center-frame userflowjs-resource-center-frame--fixed userflowjs-resource-center-frame--placement-bottom-right userflowjs-resource-center-frame--animating userflowjs-resource-center-frame--closed</value>
      <webElementGuid>7341f3b1-f6a5-4782-978f-1e6e59a5d00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b2a0ee33-14ed-45b2-aba7-5399d18d094b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bis_size</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>f4f525ad-81b1-4774-99d6-6d624b88557a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>095ba458-f647-4a70-abc0-94b707bca573</value>
      <webElementGuid>99f0c49e-4969-48f7-9a3b-17632f35cf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userflow-ui&quot;)/div[@class=&quot;userflowjs-resource-center userflowjs-theme-root&quot;]/iframe[@class=&quot;userflowjs-resource-center-frame userflowjs-resource-center-frame--fixed userflowjs-resource-center-frame--placement-bottom-right userflowjs-resource-center-frame--animating userflowjs-resource-center-frame--closed&quot;]</value>
      <webElementGuid>acd5b1af-0d32-4144-b3b3-f0840c8d2eaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userflow-ui']/div/iframe</value>
      <webElementGuid>4e615bd2-6d17-4744-bbad-93da4993ad46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c7833ec2-58d9-4151-a221-03cfad116525</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
