<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>3a59d053-404b-475f-af70-e34fb663a912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Resource Center'])[1]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.userflowjs-resource-center-icon-button.userflowjs-resource-center-close-button > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a81cf9a3-20b5-42c0-8497-7a8b6ee803b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08f5e5da-c026-4399-8cfb-befd5ea6ffc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1817df23-a53e-4204-b456-b697cf4b54e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>7b13e276-7c54-4d04-a776-276524d1ae1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>157a0b25-63b1-45a3-9702-aafb621174a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>fabdc851-83c5-486e-aae6-db0626e6ba0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 448 512</value>
      <webElementGuid>02d00d84-b602-4a5e-b25f-afcba3bdd965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;userflowjs-theme-root&quot;]/div[@class=&quot;userflowjs-resource-center-frame-root userflowjs-resource-center-frame-root--placement-bottom-right userflowjs-resource-center-frame-root--open&quot;]/div[@class=&quot;userflowjs-resource-center-header&quot;]/div[@class=&quot;userflowjs-resource-center-header-content&quot;]/button[@class=&quot;userflowjs-resource-center-icon-button userflowjs-resource-center-close-button&quot;]/svg[1]</value>
      <webElementGuid>5da6e85a-713f-452b-8449-ee27e55fa0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboard - Katalon TestOps/iframe_View all_userflowjs-resource-center-_f0d70f</value>
      <webElementGuid>0d0f5c1f-3b3f-4d3d-bff0-78d310e3d651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resource Center'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>53c583bd-6865-497c-b0c4-85290dcf4226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Demo Site'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>32290ceb-a039-456f-bca7-33e67e10d4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
