<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Valid email is required to activate pr_d77180</name>
   <tag></tag>
   <elementGuidId>84bb5f27-52ad-4eb6-98a1-8f59bf00455a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[3]/div/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form_sign_up</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>ff225a35-99ad-4c46-a56a-6d5f28ecf87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form_sign_up</value>
      <webElementGuid>22d4f47b-d9e4-4ccc-9084-349633fc4108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ca3ef305-9373-4a1a-af2d-b0707e23d3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Valid email is required to activate productsPassword Requirements1 upper and lowercase letter1 special character (e.g. @,#,$,...)At least 8 charactersDo not allow spaceLogin successful.Forgot your password?</value>
      <webElementGuid>09648418-1c38-4533-a7fe-e5a7102f8261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;SignIn_wrapSignIn__jdoQJ&quot;]/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]</value>
      <webElementGuid>a39cbb71-1fba-4e04-a622-26b9ccb3264b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form</value>
      <webElementGuid>3ef6d47d-f564-483a-a8ad-ef2b27d2c7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome back'])[1]/following::form[1]</value>
      <webElementGuid>ce8d19c7-8ee4-474f-98ab-99a2eaa2896e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/following::form[1]</value>
      <webElementGuid>72dfc4b6-1649-4a0b-a5e3-e38b4d03997d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>f1191be4-e8a5-40f9-bcc9-bc390885c10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Valid email is required to activate productsPassword Requirements1 upper and lowercase letter1 special character (e.g. @,#,$,...)At least 8 charactersDo not allow spaceLogin successful.Forgot your password?' or . = 'Valid email is required to activate productsPassword Requirements1 upper and lowercase letter1 special character (e.g. @,#,$,...)At least 8 charactersDo not allow spaceLogin successful.Forgot your password?')]</value>
      <webElementGuid>9bb1b43f-4f09-4bc3-b4d2-bacf320238de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
