<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FPFirst Project</name>
   <tag></tag>
   <elementGuidId>842bdc98-76e6-49c1-a41f-fce7cbda1ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div[2]/div/div[2]/div/a/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.project-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a2e13d9-cd77-4142-96f1-6495b503141e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>First Project</value>
      <webElementGuid>e9c146d2-ba7e-4cbe-86ae-ab3591cf3d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>project-header</value>
      <webElementGuid>7e521440-2434-4935-affa-bc26f0ec621b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>19c3b61f-5e77-4f23-9864-3535680d23fa</value>
      <webElementGuid>188deb10-e6f2-4549-acab-dc65f273e128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FPFirst Project</value>
      <webElementGuid>369ed8bf-4f41-41e0-ba55-9b36bf877190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;main-body-wrapper&quot;]/div[@class=&quot;main-body&quot;]/div[@class=&quot;dashboard-card&quot;]/div[@class=&quot;card&quot;]/a[1]/div[@class=&quot;card-header&quot;]/div[@class=&quot;project-header&quot;]</value>
      <webElementGuid>e82d460a-cca6-407d-b7f5-22139b123a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div[2]/div/div[2]/div/a/div/div</value>
      <webElementGuid>abb2d15c-59d0-4f7c-a6cf-3538f0d41775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View all projects'])[1]/following::div[4]</value>
      <webElementGuid>3e37b04e-5f56-4a43-80c0-f101345298b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Projects'])[1]/following::div[4]</value>
      <webElementGuid>984ad042-8ade-4f6c-8eac-591fec66a779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There is no data to display.'])[1]/preceding::div[6]</value>
      <webElementGuid>a94bfe34-7968-410d-976d-d9f849628b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='First Project']/parent::*</value>
      <webElementGuid>0da9e0e5-89c1-47f2-882f-7e7f5078f9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>516c240d-0742-40f1-8e73-2afd42f1f32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'First Project' and (text() = 'FPFirst Project' or . = 'FPFirst Project')]</value>
      <webElementGuid>41892a46-986d-49bd-917a-82f035b0bb56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
