<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SJShubham Jagtapsjagtapkognivera.comVie_5c490c</name>
   <tag></tag>
   <elementGuidId>61982243-8951-4430-8ef4-4338c5539363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#simple-popover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fffab51e-593f-4db7-a3ef-965b93d77926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c0a6ff81-59d0-4441-b682-6569513502aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiPopover-root MuiModal-root css-jp7szo</value>
      <webElementGuid>895ab64e-9dc4-401d-b488-19e022c34bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>simple-popover</value>
      <webElementGuid>881122e6-bd66-4c3a-b935-79fad38dbf46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SJShubham Jagtapsjagtap@kognivera.comView ProfileNotification SettingsDocumentationRelease NotesCommunity PortalSubmit a Support CaseSwitch AccountSign Out</value>
      <webElementGuid>820984b3-c64e-435f-b31f-6393df9cef11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-popover&quot;)</value>
      <webElementGuid>1cfd8537-a1b5-41ff-9871-7c06dfb6ca86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='simple-popover']</value>
      <webElementGuid>6e586c48-0752-468f-a7b5-a4bd7e4b326c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan 03, 13:17'])[2]/following::div[21]</value>
      <webElementGuid>57dc7687-34cd-4ef7-b342-f1e3b1b00691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>e57fe92c-8fd9-43af-b5ea-d4b89bd75e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'simple-popover' and (text() = 'SJShubham Jagtapsjagtap@kognivera.comView ProfileNotification SettingsDocumentationRelease NotesCommunity PortalSubmit a Support CaseSwitch AccountSign Out' or . = 'SJShubham Jagtapsjagtap@kognivera.comView ProfileNotification SettingsDocumentationRelease NotesCommunity PortalSubmit a Support CaseSwitch AccountSign Out')]</value>
      <webElementGuid>c52efbb9-c9b9-4bdd-8670-1184feed5350</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
